dist: xenial
language: go
go:
    - 1.14.x

addons:
 snaps:
  - name: hugo
    channel: extended/stable

#install:
#    - export GO111MODULE=on
#    - go get github.com/gohugoio/hugo_extended@v0.74.3
   
before_script:
    - rm -rf public 2> /dev/null

script:
    - hugo
    - echo "$CNAME_URL" > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  verbose: true
  keep-history: false
  local-dir: public
  on:
    branch: v2
